server:
  port: 8083

spring:
  application:
    name: authentication-service
  profiles:
    active: local

jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
