name: Docker Build and Publish

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run services
        run: |
          docker-compose up -d --build
          sleep 30
          docker ps -a

      - name: Shut down services
        if: always()
        run: |
          docker-compose down

  push-to-dockerhub:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: |
          SERVICES="eureka gateway authentication-service email-service ventas-back recommendation-service"
          for SERVICE in $SERVICES; do
            docker build -t $DOCKERHUB_USERNAME/$SERVICE:latest $SERVICE
            docker push $DOCKERHUB_USERNAME/$SERVICE:latest
          done
