version: '3.8'

services:
  # PostgreSQL para authentication-service
  auth-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb

  # PostgreSQL para ventas-back
  ventas-db:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ventasuser
      POSTGRES_PASSWORD: ventaspass
      POSTGRES_DB: ventasdb

  # PostgreSQL para recommendation-service
  recommendation-db:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: recouser
      POSTGRES_PASSWORD: recopass
      POSTGRES_DB: recodb

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka
  kafka:  # <- Aquí estaba el error: faltaba esta indentación
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
